### ISSUE TITLE
Access to .rda files 

### ISSUE THREAD

**Issue by rachelkunowski** [EpiModel/EpiModelHIV#57]
Hello, when I try running the msm-test-script.R file, it tries to read 3 .rda files that I can't find in the GitHub:

netstats <- readRDS(file.path(scr.dir, "data/artnet.NetStats.Atlanta.rda"))
epistats <- readRDS(file.path(scr.dir, "data/artnet.EpiStats.Atlanta.rda"))
est <- readRDS(file.path(scr.dir, "data/artnet.NetEst.Atlanta.rda"))

Would I be able to get access to these .rda files so I can run this script? Thank you!

**Comment by smjenness** [comment]
These are files that are saved in the estimation step of the scripts. Your specific names/file paths may need to be modified.
